# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(720, 592)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.plot_fr = QtWidgets.QFrame(self.centralwidget)
        self.plot_fr.setMinimumSize(QtCore.QSize(500, 200))
        self.plot_fr.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.plot_fr.setFrameShadow(QtWidgets.QFrame.Raised)
        self.plot_fr.setObjectName("plot_fr")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.plot_fr)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.plot = MplWidget(self.plot_fr)
        self.plot.setMinimumSize(QtCore.QSize(150, 150))
        self.plot.setStatusTip("")
        self.plot.setObjectName("plot")
        self.verticalLayout_2.addWidget(self.plot)
        self.gridLayout.addWidget(self.plot_fr, 0, 0, 2, 1)
        self.settings_fr = QtWidgets.QFrame(self.centralwidget)
        self.settings_fr.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.settings_fr.setFrameShadow(QtWidgets.QFrame.Raised)
        self.settings_fr.setObjectName("settings_fr")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.settings_fr)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.One = QtWidgets.QGroupBox(self.settings_fr)
        self.One.setObjectName("One")
        self.verticalLayout_3.addWidget(self.One)
        self.Two = QtWidgets.QGroupBox(self.settings_fr)
        self.Two.setObjectName("Two")
        self.verticalLayout_3.addWidget(self.Two)
        self.gridLayout.addWidget(self.settings_fr, 0, 1, 1, 1)
        self.table_fr = QtWidgets.QFrame(self.centralwidget)
        self.table_fr.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.table_fr.setFrameShadow(QtWidgets.QFrame.Raised)
        self.table_fr.setObjectName("table_fr")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.table_fr)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.table = QtWidgets.QTableWidget(self.table_fr)
        self.table.setObjectName("table")
        self.table.setColumnCount(0)
        self.table.setRowCount(0)
        self.horizontalLayout.addWidget(self.table)
        self.gridLayout.addWidget(self.table_fr, 2, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menu = QtWidgets.QMenuBar(MainWindow)
        self.menu.setGeometry(QtCore.QRect(0, 0, 720, 22))
        self.menu.setObjectName("menu")
        self.File_opt = QtWidgets.QMenu(self.menu)
        self.File_opt.setObjectName("File_opt")
        MainWindow.setMenuBar(self.menu)
        self.fopen = QtWidgets.QAction(MainWindow)
        self.fopen.setObjectName("fopen")
        self.fsave = QtWidgets.QAction(MainWindow)
        self.fsave.setObjectName("fsave")
        self.plrand = QtWidgets.QAction(MainWindow)
        self.plrand.setObjectName("plrand")
        self.File_opt.addAction(self.fopen)
        self.File_opt.addAction(self.fsave)
        self.File_opt.addSeparator()
        self.File_opt.addAction(self.plrand)
        self.menu.addAction(self.File_opt.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.One.setTitle(_translate("MainWindow", "one"))
        self.Two.setTitle(_translate("MainWindow", "two"))
        self.File_opt.setTitle(_translate("MainWindow", "File"))
        self.fopen.setText(_translate("MainWindow", "Open exist"))
        self.fsave.setText(_translate("MainWindow", "Save as"))
        self.plrand.setText(_translate("MainWindow", "Random Plot?"))
from mplwidget import MplWidget
